### ISSUE TITLE
诚邀您加入我们的React文档翻译组

### ISSUE THREAD

**Issue by discountry** [alivebao/React-Tutorial#1]
你好，我是[从零学习前端开发专栏](https://zhuanlan.zhihu.com/icode)的作者余博伦，我们最近成立了一个翻译react文档的翻译组，看到您也在进行翻译工作，本着开源的精神，为了避免重复劳动，诚邀您加入我们的翻译小组，项目地址：
https://discountry.github.io/react/

**Comment by alivebao** [comment]
谢谢，我先完成这个系列吧，完成后与您联系：）
